version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: $APP_STACKS_EXPLORER_IP
      APP_PORT: $APP_STACKS_EXPLORER_PORT
      PROXY_AUTH_WHITELIST: "/stacks-blockchain-api/*"


  stacks-explorer:
    image: hirosystems/explorer:1.219.1
    init: true
    restart: on-failure
    user: "1000:1000"
    stop_grace_period: 1m
    environment:
      #Hiro scuffed the env vars so running a hardcoded prebuilt version
      NEXT_PUBLIC_MAINNET_API_SERVER: http://${DEVICE_HOSTNAME}.local:${APP_STACKS_API_PORT}
      NEXT_PUBLIC_TESTNET_API_SERVER: https://stacks-node-api.testnet.stacks.co
      NEXT_PUBLIC_LEGACY_EXPLORER_API_SERVER: https://explorer-api.legacy.blockstack.org
      NEXT_PUBLIC_DEPLOYMENT_URL: http://${DEVICE_HOSTNAME}.local:4009
      NEXT_PUBLIC_MAINNET_ENABLED: "true"
      NEXT_PUBLIC_DEFAULT_POLLING_INTERVAL: "10000"
      NEXT_MEMPOOL_SPACE_URL: "http://${DEVICE_HOSTNAME}.local:${APP_MEMPOOL_PORT:-3006}"
      NODE_ENV: production
      PORT: $APP_STACKS_EXPLORER_PORT
    ports:
      - $APP_STACKS_EXPLORER_PORT:$APP_STACKS_EXPLORER_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_EXPLORER_IP
  


  stacks-blockchain:
    image: blockstack/stacks-blockchain:3.0.0.0.2
    init: true
    restart: on-failure
    stop_grace_period: 15m
    env_file:
      - ${APP_DATA_DIR}/data/config/setup.env
    command: 
      [
        "/bin/stacks-node",
        "start",
        "--config",
        "/src/stacks-blockchain/Config.toml",
      ]
    ports:
      - $APP_STACKS_CORE_RPC_PORT:$APP_STACKS_CORE_RPC_PORT
      - $APP_STACKS_CORE_P2P_PORT:$APP_STACKS_CORE_P2P_PORT
    volumes:
      - ${APP_DATA_DIR}/data/config:/src/stacks-blockchain
      - ${APP_DATA_DIR}/data/stacks-blockchain:/app/stacks-blockchain/data
    networks:
      default:
        ipv4_address: $APP_STACKS_BLOCKCHAIN_IP
    depends_on:
      - stacks-blockchain-api

  stacks-blockchain-api:
    image: hirosystems/stacks-blockchain-api:v8.3.0-beta.1
    init: true
    restart: on-failure
    #user: 0:0
    stop_grace_period: 15m
    env_file:
      - ${APP_DATA_DIR}/data/config/setup.env
    volumes:
      - ${APP_DATA_DIR}/data/bns-data:/bns-data
      - ${APP_DATA_DIR}/data/event-replay:/tmp/event-replay
    ports:
      - $APP_STACKS_CORE_EVENT_PORT:$APP_STACKS_CORE_EVENT_PORT
      - $APP_STACKS_API_PORT:$APP_STACKS_API_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_API_IP
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    init: true
    shm_size: ${PG_SHMSIZE:-256MB}
    restart: on-failure
    stop_grace_period: 15m
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD:-postgres}
    env_file:
      - ${APP_DATA_DIR}/data/config/setup.env
    ports:
      - $APP_STACKS_DB_PORT:$APP_STACKS_DB_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_DB_IP
